export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function SolutionsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
